### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by tomas-hartman** [tomas-hartman/clean-the-mess#12]

**Comment by tomas-hartman** [comment]
# todos:

- [ ] enhance search engine so it supports search in url
- [ ] fix renderer, dedupe
- [ ] later: implement logic for search in overview

**Comment by tomas-hartman** [comment]
Divided into separate issues. Closing now.
